version: '2.0'

services:

  swcollector:
    container_name: swcollector
    restart: always
    build: ./sw
    image: app_swcollector
    ports:
      - "2003:2003"
    volumes:
      - /data/2003/cfg.json:/usr/local/swcollector/cfg.json
    network_mode: "bridge"
  
  swcollector-old:
    container_name: swcollector-old
    restart: always
    build: ./sw-old
    image: app_swcollector-old
    ports:
      - "2002:2002"
    volumes:
      - /data/2002/cfg.json:/usr/local/swcollector/cfg.json
    network_mode: "bridge"

  hkswcollector:
    container_name: hkswcollector
    restart: always
    build: ./hksw
    image: app_hkswcollector
    ports:
      - "2004:2004"
    volumes:
      - /data/2004/cfg.json:/usr/local/swcollector/cfg.json
    network_mode: "bridge"
